{% set name = "wasabi" %}
{% set version = "0.10.1" %}
{% set sha256sum = "c8e372781be19272942382b14d99314d175518d7822057cb7a97010c4259d249" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - pytest <4
  imports:
    - {{ name }}
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}


about:
  home: http://github.com/ines/wasabi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight console printing and formatting toolkit

  dev_url: https://github.com/ines/wasabi
  doc_url: https://github.com/ines/wasabi#-api

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
